<?php

return [
    'id'    => 'youtube-style',
    'label' => 'YouTube Style',

    // Colors
    'accent_color'        => 'transparent',
    'accent_text'         => '#0f0f0f',
    'item_bg'             => 'transparent',
    'item_text'           => '#0f0f0f',
    'item_hover_bg'       => 'rgba(0, 0, 0, 0.05)',
    'item_border'         => 'transparent',
    'item_border_hover'   => 'transparent',
    'list_bg'             => '#ffffff',
    'header_bg'           => '#ffffff',
    'header_text_color'   => '#0f0f0f',
    'container_bg'        => '#ffffff',
    'container_shadow'    => 'none',
    'badge_bg'            => 'rgba(0,0,0,0.8)',
    'badge_text'          => '#ffffff',
    'now_playing_bg'      => 'rgba(0,0,0,0.7)',
    'now_playing_text'    => '#ffffff',
    'playing_label_color' => '#065fd4',
    'meta_opacity'        => '1',
    // Dimensions
    'item_radius'         => '0px',
    'item_padding'        => '4px 8px 4px 0',
    'item_gap'            => '0px',
    'panel_width'         => '400px',
    'max_width'           => '1000px',
    'playlist_height_mode' => 'sync',
    'panel_max_height'    => '360px',
    'player_height'       => '360px',
    'player_radius'       => '12px',
    'container_radius'    => '12px',
    'gap'                 => '16px',
    'thumb_width'         => '100px',
    'thumb_radius'        => '4px',
    'header_size'         => '1.6rem',
    'header_transform'    => 'none',
    'header_spacing'      => '0',
    // Display options (POC fields)
    'skin'                => 'default',
    'position'            => 'right',
    // Features
    'show_header'         => true,
    'header_text'         => 'Up Next',
    'show_count'          => false,
    'show_icon'           => false,
    'show_numbers'        => true,
    'show_thumbnails'     => true,
    'show_meta'           => true,
    'show_duration_badge' => true,
    'show_duration_in_list'=> true,
    'play_icon'           => 'hidden',
    'show_part_label'     => false,
    'show_playing_label'  => false,
    'playing_label_text'  => 'Now Playing',
    'autoplay_next'       => false,
];
